### ISSUE TITLE
Crash on x86_64 with non debug build

### ISSUE THREAD

**Issue by parkerlreed** [libretro/nxengine-libretro#63]
Arch Linux
RetroArch GIT with debug enabled (ef4d24600e)
Nxengine from Core Downloader and compiled myself without debug crash with this error

```
[parker@stealth ~]$ retroarch
[CDROM] No sg devices found and sg kernel module is not loaded.
munmap_chunk(): invalid pointer
Aborted (core dumped)
```

```
           PID: 78871 (retroarch)
           UID: 1000 (parker)
           GID: 1000 (parker)
        Signal: 6 (ABRT)
     Timestamp: Fri 2019-12-20 23:14:53 EST (47s ago)
  Command Line: retroarch
    Executable: /usr/bin/retroarch
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (parker)
       Boot ID: 621e0b87ac334aa185cc3a058c674c50
    Machine ID: 175eb21d26bc4b75a833309c038d32c8
      Hostname: stealth
       Storage: /var/lib/systemd/coredump/core.retroarch.1000.621e0b87ac334aa185cc3a058c674c50.78871.1576901693000000000000.lz4
       Message: Process 78871 (retroarch) of user 1000 dumped core.
                
                Stack trace of thread 78871:
                #0  0x00007f4cf9933f25 raise (libc.so.6 + 0x3bf25)
                #1  0x00007f4cf991d897 abort (libc.so.6 + 0x25897)
                #2  0x00007f4cf9977258 __libc_message (libc.so.6 + 0x7f258)
                #3  0x00007f4cf997e77a malloc_printerr (libc.so.6 + 0x8677a)
                #4  0x00007f4cf997ea2c munmap_chunk (libc.so.6 + 0x86a2c)
                #5  0x00007f4cf17f6625 n/a (/home/parker/.config/retroarch/cores/nxengine_libretro.so + 0xb625)
                #6  0x0000000000000004 n/a (n/a + 0x0)
```

Nxengine with debug enabled works, so this may not be so helpful

```
#0  0x00007f4cf9933f25 in raise () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007f4cf991d897 in abort () from /usr/lib/libc.so.6
No symbol table info available.
#2  0x00007f4cf9977258 in __libc_message () from /usr/lib/libc.so.6
No symbol table info available.
#3  0x00007f4cf997e77a in malloc_printerr () from /usr/lib/libc.so.6
No symbol table info available.
#4  0x00007f4cf997ea2c in munmap_chunk () from /usr/lib/libc.so.6
No symbol table info available.
#5  0x00007f4cf17f6625 in CreateObject(int, int, int, int, int, int, Object*, unsigned int) [clone .cold] () from /home/parker/.config/retroarch/cores/nxengine_libretro.so
No symbol table info available.
#6  0x0000000000000000 in ?? ()
No symbol table info available.
```

**Comment by hizzlekizzle** [comment]
Yeah, same thing here. Looks like the snap package gives a full backtrace, though:

```
*** Error in `/snap/retroarch/347/usr/local/bin/retroarch': munmap_chunk(): invalid pointer: 0x00007ffede6b6af0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fa0ff9057e5]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x1a8)[0x7fa0ff912698]
/home/asdf/snap/retroarch/347/.config/retroarch/cores/nxengine_libretro.so(+0xad15)[0x7fa0ec3a6d15]
[0x7ffede6b6ef0]
======= Memory map: ========
00400000-011a0000 r-xp 00000000 07:06 37598                              /snap/retroarch/347/usr/local/bin/retroarch
0139f000-013c4000 r--p 00d9f000 07:06 37598                              /snap/retroarch/347/usr/local/bin/retroarch
013c4000-013d5000 rw-p 00dc4000 07:06 37598                              /snap/retroarch/347/usr/local/bin/retroarch
013d5000-01bbd000 rw-p 00000000 00:00 0 
02cae000-041e4000 rw-p 00000000 00:00 0                                  [heap]
7fa0d4000000-7fa0d492b000 rw-p 00000000 00:00 0 
7fa0d492b000-7fa0d8000000 ---p 00000000 00:00 0 
7fa0e0000000-7fa0e0021000 rw-p 00000000 00:00 0 
7fa0e0021000-7fa0e4000000 ---p 00000000 00:00 0 
7fa0e7f1e000-7fa0e7f1f000 ---p 00000000 00:00 0 
7fa0e7f1f000-7fa0e871f000 rw-p 00000000 00:00 0 
7fa0ec39c000-7fa0ec427000 r-xp 00000000 08:06 21495933                   /home/asdf/snap/retroarch/347/.config/retroarch/cores/nxengine_libretro.so
7fa0ec427000-7fa0ec626000 ---p 0008b000 08:06 21495933                   /home/asdf/snap/retroarch/347/.config/retroarch/cores/nxengine_libretro.so
7fa0ec626000-7fa0ec629000 r--p 0008a000 08:06 21495933                   /home/asdf/snap/retroarch/347/.config/retroarch/cores/nxengine_libretro.so
7fa0ec629000-7fa0ec669000 rw-p 0008d000 08:06 21495933                   /home/asdf/snap/retroarch/347/.config/retroarch/cores/nxengine_libretro.so
7fa0ec669000-7fa0ec814000 rw-p 00000000 00:00 0 
7fa0ec814000-7fa0ec81c000 r-xp 00000000 07:06 36159                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libpciaccess.so.0.11.1
7fa0ec81c000-7fa0eca1c000 ---p 00008000 07:06 36159                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libpciaccess.so.0.11.1
7fa0eca1c000-7fa0eca1d000 r--p 00008000 07:06 36159                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libpciaccess.so.0.11.1
7fa0eca1d000-7fa0eca1e000 rw-p 00009000 07:06 36159                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libpciaccess.so.0.11.1
7fa0eca1e000-7fa0eca29000 r-xp 00000000 07:06 35971                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libdrm_radeon.so.1.0.1
7fa0eca29000-7fa0ecc28000 ---p 0000b000 07:06 35971                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libdrm_radeon.so.1.0.1
7fa0ecc28000-7fa0ecc29000 r--p 0000a000 07:06 35971                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libdrm_radeon.so.1.0.1
7fa0ecc29000-7fa0ecc2a000 rw-p 0000b000 07:06 35971                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libdrm_radeon.so.1.0.1
7fa0ecc2a000-7fa0ecc31000 r-xp 00000000 07:06 35967                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2.0.0
7fa0ecc31000-7fa0ece30000 ---p 00007000 07:06 35967                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2.0.0
7fa0ece30000-7fa0ece31000 r--p 00006000 07:06 35967                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2.0.0
7fa0ece31000-7fa0ece32000 rw-p 00007000 07:06 35967                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2.0.0
7fa0ece32000-7fa0ece54000 r-xp 00000000 07:06 35963                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libdrm_intel.so.1.0.0
7fa0ece54000-7fa0ed054000 ---p 00022000 07:06 35963                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libdrm_intel.so.1.0.0
7fa0ed054000-7fa0ed055000 r--p 00022000 07:06 35963                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libdrm_intel.so.1.0.0
7fa0ed055000-7fa0ed056000 rw-p 00023000 07:06 35963                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libdrm_intel.so.1.0.0
7fa0ed056000-7fa0ed936000 r-xp 00000000 07:06 35643                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/dri/i965_dri.so
7fa0ed936000-7fa0edb36000 ---p 008e0000 07:06 35643                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/dri/i965_dri.so
7fa0edb36000-7fa0edb86000 r--p 008e0000 07:06 35643                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/dri/i965_dri.so
7fa0edb86000-7fa0edb91000 rw-p 00930000 07:06 35643                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/dri/i965_dri.so
7fa0edb91000-7fa0edc36000 rw-p 00000000 00:00 0 
7fa0edc36000-7fa0edc37000 ---p 00000000 00:00 0 
7fa0edc37000-7fa0ee473000 rw-p 00000000 00:00 0 
7fa0ee473000-7fa0ee476000 r-xp 00000000 07:06 25376                      /snap/retroarch/347/lib/x86_64-linux-gnu/libkeyutils.so.1.5
7fa0ee476000-7fa0ee675000 ---p 00003000 07:06 25376                      /snap/retroarch/347/lib/x86_64-linux-gnu/libkeyutils.so.1.5
7fa0ee675000-7fa0ee676000 r--p 00002000 07:06 25376                      /snap/retroarch/347/lib/x86_64-linux-gnu/libkeyutils.so.1.5
7fa0ee676000-7fa0ee677000 rw-p 00003000 07:06 25376                      /snap/retroarch/347/lib/x86_64-linux-gnu/libkeyutils.so.1.5
7fa0ee677000-7fa0ee681000 r-xp 00000000 07:06 36094                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7fa0ee681000-7fa0ee880000 ---p 0000a000 07:06 36094                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7fa0ee880000-7fa0ee881000 r--p 00009000 07:06 36094                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7fa0ee881000-7fa0ee882000 rw-p 0000a000 07:06 36094                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7fa0ee882000-7fa0ee885000 r-xp 00000000 07:12 2139                       /lib/x86_64-linux-gnu/libcom_err.so.2.1
7fa0ee885000-7fa0eea84000 ---p 00003000 07:12 2139                       /lib/x86_64-linux-gnu/libcom_err.so.2.1
7fa0eea84000-7fa0eea85000 r--p 00002000 07:12 2139                       /lib/x86_64-linux-gnu/libcom_err.so.2.1
7fa0eea85000-7fa0eea86000 rw-p 00003000 07:12 2139                       /lib/x86_64-linux-gnu/libcom_err.so.2.1
7fa0eea86000-7fa0eeab2000 r-xp 00000000 07:06 36088                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7fa0eeab2000-7fa0eecb1000 ---p 0002c000 07:06 36088                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7fa0eecb1000-7fa0eecb3000 r--p 0002b000 07:06 36088                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7fa0eecb3000-7fa0eecb4000 rw-p 0002d000 07:06 36088                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7fa0eecb4000-7fa0eecb5000 rw-p 00000000 00:00 0 
7fa0eecb5000-7fa0eed78000 r-xp 00000000 07:06 36092                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7fa0eed78000-7fa0eef78000 ---p 000c3000 07:06 36092                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7fa0eef78000-7fa0eef85000 r--p 000c3000 07:06 36092                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7fa0eef85000-7fa0eef87000 rw-p 000d0000 07:06 36092                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7fa0eef87000-7fa0eefae000 r-xp 00000000 07:06 36089                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libkj-0.5.3.so
7fa0eefae000-7fa0ef1ae000 ---p 00027000 07:06 36089                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libkj-0.5.3.so
7fa0ef1ae000-7fa0ef1af000 r--p 00027000 07:06 36089                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libkj-0.5.3.so
7fa0ef1af000-7fa0ef1b0000 rw-p 00028000 07:06 36089                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libkj-0.5.3.so
7fa0ef1b0000-7fa0ef1c7000 r-xp 00000000 07:06 35914                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0
7fa0ef1c7000-7fa0ef3c6000 ---p 00017000 07:06 35914                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0
7fa0ef3c6000-7fa0ef3c7000 r--p 00016000 07:06 35914                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0
7fa0ef3c7000-7fa0ef3c8000 rw-p 00017000 07:06 35914                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0
7fa0ef3c8000-7fa0ef3da000 r-xp 00000000 07:12 2168                       /lib/x86_64-linux-gnu/libgpg-error.so.0.17.0
7fa0ef3da000-7fa0ef5da000 ---p 00012000 07:12 2168                       /lib/x86_64-linux-gnu/libgpg-error.so.0.17.0
7fa0ef5da000-7fa0ef5db000 r--p 00012000 07:12 2168                       /lib/x86_64-linux-gnu/libgpg-error.so.0.17.0
7fa0ef5db000-7fa0ef5dc000 rw-p 00013000 07:12 2168                       /lib/x86_64-linux-gnu/libgpg-error.so.0.17.0
7fa0ef5dc000-7fa0ef5f3000 r-xp 00000000 07:12 2250                       /lib/x86_64-linux-gnu/libresolv-2.23.so
7fa0ef5f3000-7fa0ef7f3000 ---p 00017000 07:12 2250                       /lib/x86_64-linux-gnu/libresolv-2.23.so
7fa0ef7f3000-7fa0ef7f4000 r--p 00017000 07:12 2250                       /lib/x86_64-linux-gnu/libresolv-2.23.so
7fa0ef7f4000-7fa0ef7f5000 rw-p 00018000 07:12 2250                       /lib/x86_64-linux-gnu/libresolv-2.23.so
7fa0ef7f5000-7fa0ef7f7000 rw-p 00000000 00:00 0 
7fa0ef7f7000-7fa0ef86a000 r-xp 00000000 07:06 35739                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libFLAC.so.8.3.0
7fa0ef86a000-7fa0efa6a000 ---p 00073000 07:06 35739                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libFLAC.so.8.3.0
7fa0efa6a000-7fa0efa6b000 r--p 00073000 07:06 35739                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libFLAC.so.8.3.0
7fa0efa6b000-7fa0efa6c000 rw-p 00074000 07:06 35739                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libFLAC.so.8.3.0
7fa0efa6c000-7fa0efa82000 r-xp 00000000 07:12 2212                       /lib/x86_64-linux-gnu/libnsl-2.23.so
7fa0efa82000-7fa0efc81000 ---p 00016000 07:12 2212                       /lib/x86_64-linux-gnu/libnsl-2.23.so
7fa0efc81000-7fa0efc82000 r--p 00015000 07:12 2212                       /lib/x86_64-linux-gnu/libnsl-2.23.so
7fa0efc82000-7fa0efc83000 rw-p 00016000 07:12 2212                       /lib/x86_64-linux-gnu/libnsl-2.23.so
7fa0efc83000-7fa0efc85000 rw-p 00000000 00:00 0 
7fa0efc85000-7fa0efca6000 r-xp 00000000 07:06 36031                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7fa0efca6000-7fa0efea5000 ---p 00021000 07:06 36031                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7fa0efea5000-7fa0efea6000 r--p 00020000 07:06 36031                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7fa0efea6000-7fa0efea7000 rw-p 00021000 07:06 36031                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7fa0efea7000-7fa0efeb8000 r-xp 00000000 07:06 36234                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7fa0efeb8000-7fa0f00b8000 ---p 00011000 07:06 36234                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7fa0f00b8000-7fa0f00b9000 r--p 00011000 07:06 36234                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7fa0f00b9000-7fa0f00ba000 rw-p 00012000 07:06 36234                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7fa0f00ba000-7fa0f00eb000 r-xp 00000000 07:06 36074                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7fa0f00eb000-7fa0f02eb000 ---p 00031000 07:06 36074                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7fa0f02eb000-7fa0f02ec000 r--p 00031000 07:06 36074                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7fa0f02ec000-7fa0f02ed000 rw-p 00032000 07:06 36074                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7fa0f02ed000-7fa0f0346000 r-xp 00000000 07:06 36151                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7fa0f0346000-7fa0f0545000 ---p 00059000 07:06 36151                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7fa0f0545000-7fa0f054f000 r--p 00058000 07:06 36151                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7fa0f054f000-7fa0f0551000 rw-p 00062000 07:06 36151                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7fa0f0551000-7fa0f0702000 r-xp 00000000 07:06 36353                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7fa0f0702000-7fa0f0901000 ---p 001b1000 07:06 36353                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7fa0f0901000-7fa0f0909000 r--p 001b0000 07:06 36353                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7fa0f0909000-7fa0f090b000 rw-p 001b8000 07:06 36353                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7fa0f090b000-7fa0f090c000 rw-p 00000000 00:00 0 
7fa0f090c000-7fa0f098b000 r-xp 00000000 07:06 36025                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7fa0f098b000-7fa0f0b8a000 ---p 0007f000 07:06 36025                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7fa0f0b8a000-7fa0f0b8b000 r--p 0007e000 07:06 36025                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7fa0f0b8b000-7fa0f0b8c000 rw-p 0007f000 07:06 36025                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7fa0f0b8c000-7fa0f0bc0000 r-xp 00000000 07:06 36123                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7fa0f0bc0000-7fa0f0dbf000 ---p 00034000 07:06 36123                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7fa0f0dbf000-7fa0f0dc1000 r--p 00033000 07:06 36123                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7fa0f0dc1000-7fa0f0dc2000 rw-p 00035000 07:06 36123                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7fa0f0dc2000-7fa0f0df4000 r-xp 00000000 07:06 36056                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7fa0f0df4000-7fa0f0ff3000 ---p 00032000 07:06 36056                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7fa0f0ff3000-7fa0f0ff4000 r--p 00031000 07:06 36056                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7fa0f0ff4000-7fa0f0ff5000 rw-p 00032000 07:06 36056                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7fa0f0ff5000-7fa0f103c000 r-xp 00000000 07:06 36038                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7fa0f103c000-7fa0f123b000 ---p 00047000 07:06 36038                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7fa0f123b000-7fa0f123d000 r--p 00046000 07:06 36038                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7fa0f123d000-7fa0f123f000 rw-p 00048000 07:06 36038                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7fa0f123f000-7fa0f12ba000 r-xp 00000000 07:06 36147                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/liborc-0.4.so.0.25.0
7fa0f12ba000-7fa0f14b9000 ---p 0007b000 07:06 36147                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/liborc-0.4.so.0.25.0
7fa0f14b9000-7fa0f14bb000 r--p 0007a000 07:06 36147                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/liborc-0.4.so.0.25.0
7fa0f14bb000-7fa0f14bf000 rw-p 0007c000 07:06 36147                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/liborc-0.4.so.0.25.0
7fa0f14bf000-7fa0f14c6000 r-xp 00000000 07:06 36137                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libogg.so.0.8.2
7fa0f14c6000-7fa0f16c6000 ---p 00007000 07:06 36137                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libogg.so.0.8.2
7fa0f16c6000-7fa0f16c7000 r--p 00007000 07:06 36137                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libogg.so.0.8.2
7fa0f16c7000-7fa0f16c8000 rw-p 00008000 07:06 36137                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libogg.so.0.8.2
7fa0f16c8000-7fa0f16d2000 r-xp 00000000 07:06 36135                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0
7fa0f16d2000-7fa0f18d1000 ---p 0000a000 07:06 36135                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0
7fa0f18d1000-7fa0f18d2000 r--p 00009000 07:06 36135                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0
7fa0f18d2000-7fa0f18d3000 rw-p 0000a000 07:06 36135                      /snap/retroarch/347/usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0
7fa0f18d3000-7fa0f18e6000 r-xp 00000000 07:06 25360                      /snap/retroarch/347/lib/x86_64-linux-gnu/libbsd.so.0.8.2
7fa0f18e6000-7fa0f1ae5000 ---p 00013000 07:06 25360                      /snap/retroarch/347/lib/x86_64-linux-gnu/libbsd.so.0.8.2Aborted (core dumped)
```

**Comment by parkerlreed** [comment]
Also broken on the Switch it seems (I don't have console output but the core crashes back to Switch when loading so I assume it's very possibly related)

**Comment by parkerlreed** [comment]
@hizzlekizzle Give the latest build from core downloader a shot. It's working for me now.

**Comment by hizzlekizzle** [comment]
Yeah, seems fine here. Guess I'll go ahead and close it out. Feel free to reopen if needed.
