### ISSUE TITLE
Music doesn't play, game crashes

### ISSUE THREAD

**Issue by Jackson89524** [libretro/nxengine-libretro#97]
I found these issues when coming back to the game, did further testing on a fresh install of Retroarch. Music doesn't play in any instance from the title screen to
Game crashes seemingly randomly, or upon certain conditions

**Comment by Uukrull** [comment]
This also happens to me with the win64 version of Retroarch, but if I compile the nxengine_libretro.dll myself it works without problems so something must be wrong with the buildbot.

**Comment by Uukrull** [comment]
btw, I'm using the mingw that comes installed for Kodi:

MINGW64_NT-10.0-19044 3.2.0-340.x86_64 2021-07-02 08:36 UTC x86_64 Msys

I don't know if that makes a difference.

**Comment by Jackson89524** [comment]
I didn't know there was a way to find previous versions of cores, but your core seems to work. Thanks for helping me with this!

**Comment by bslenul** [comment]
Might be a Windows only issue? Musics play fine and no crash on my Android phone and my Linux Mint VM.

It's also fine on Windows if I build the core with DEBUG=1 or with -O1 or lower, not sure if this is helpful for the devs but I got this:
```
#0  drum_gen (num_samples=3087, m_channel=10) at nxengine/sound/org.cpp:682
        pos2 = 0
        iratio = <optimized out>
        chan = 0x7ffede13e4a0 <note_channel+800>
        audioval = <optimized out>
        volume_ratio = 0.49803921568627452
        wave = 232
        pos1 = 0
        i = 0
        volume_left_ratio = 1
        volume_right_ratio = 0
        chan = <optimized out>
        pos1 = <optimized out>
        pos2 = <optimized out>
        iratio = <optimized out>
        audioval = <optimized out>
        i = <optimized out>
        volume_ratio = <optimized out>
        volume_left_ratio = <optimized out>
        volume_right_ratio = <optimized out>
        wave = <optimized out>
#1  NextBeat (m=10) at nxengine/sound/org.cpp:861
        chan = 0x7ffede13e4a0 <note_channel+800>
        track = 0x7ffede10375c <song+400284>
        note = <optimized out>
        len = 3087
        chan = <optimized out>
        track = <optimized out>
        note = <optimized out>
        len = <optimized out>
#2  generate_music () at nxengine/sound/org.cpp:743
        m = 10
        beats_left = 2
        out_position = 6174
#3  0x00007ffeddfe8be5 in org_run () at nxengine/sound/org.cpp:705
No locals.
#4  0x00007ffeddfe6043 in run_tick () at nxengine/main.cpp:274
No locals.
#5  gameloop () at nxengine/main.cpp:170
No locals.
#6  run_main () at nxengine/main.cpp:245
No locals.
#7  0x00007ffeddfe597d in retro_run () at nxengine/libretro/libretro.cpp:325
        frame_cnt = 1198
        samples = {0, 0, 0, 0, 17376, 29951, 513, 0, 2768, 29958, 513, 0 <repeats 13 times>, 17184, 27003, 32759, 0, 16, 0, 0, 0, -2656, 29631, 40, 0, 17458, 26714, 32759, 0, 2768, 29958, 513, 0, -5728, 26865, 32759, 0, 0, 0, 0, 0, -2240, 29631, 40, 0, 15200, 26993, 32759, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 83, 0 <repeats 11 times>, -1, -1, 0, 0, -1, 0, 0, 0, 0, 16128, 0, 0, -1, -1, 0, 0, -1, 0, 0, 0, -1, -1, 0, 0, -1, 0, 0, 0, 0, 0, 3, 0, -2496, 29631, 40, 0, -20524, 26714, 32759, 0, 13184, 26995, 32759, 0, 83, 0, 513, 0, -1744, 29631, 40, 0, 0, 0, 0, 0, -2240, 29631, 40, 0, 15200, 26993, 32759, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 83, 0 <repeats 15 times>, 18896, 26993, 32759, 0, 17872, 26994, 32759, 0, 13184, 26995, 32759, 0, 29792, 0, 84, 0, 15781, 26970, 32759, 0, 25603, 26776, 32759, 0 <repeats 13 times>...}
        frames = <optimized out>
#8  0x00007ff76856000b in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```
Info reg:
```
rax            0x0                 0
rbx            0xc10               3088
rcx            0xc10               3088
rdx            0x201096b528e       2203476251278
rsi            0x201096b528e       2203476251278
rdi            0x181e              6174
rbp            0x1820              0x1820
rsp            0x2873bff330        0x2873bff330
r8             0x1820              6176
r9             0x0                 0
r10            0x101040106ff0006   72343471473491974
r11            0xffff7b06          4294933254
r12            0x7ffede13e4a0      140732624266400
r13            0x181f              6175
r14            0x7c                124
r15            0x7ffede0a1bc0      140732623625152
rip            0x7ffeddfe7f7e      0x7ffeddfe7f7e <generate_music()+974>
eflags         0x10213             [ CF AF IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x2b                43
es             0x2b                43
fs             0x53                83
gs             0x2b                43
```

**Comment by LibretroAdmin** [comment]
I can confirm this to be the case. Is it some mingw-w64/GCC issue at a certain cutoff point? I get no more music on Windows, which definitely did work before.

**Comment by bslenul** [comment]
Looks good, music is now playing properly and it doesn't crash anymore! 👍

**Comment by LibretroAdmin** [comment]
Pushed this commit -
https://github.com/libretro/nxengine-libretro/commit/e271c6262d73f07e5d92d285503f1c049801c51a

@Jackson89524 Let me know if this can be closed after testing.

**Comment by Jackson89524** [comment]
Just tested it, seems fine, no crash in Mimiga village and music plays, feel free to close!
